import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {GLTFLoader} from '../dist/assets/vendor/GLTFLoader.js';
import {clone} from '../dist/assets/vendor/utils/SkeletonUtils.js';
globalThis.self=globalThis;
globalThis.createImageBitmap=async()=>({width:1024,height:1024,close(){}});
for(const name of ['Knight','Mage','Barbarian','Rogue_Hooded']){const b=await fs.readFile(new URL(`../dist/assets/models/${name}.glb`,import.meta.url));const data=await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');const instance=clone(data.scene);const mixer=new THREE.AnimationMixer(instance);assert.ok(data.animations.length===14);mixer.clipAction(data.animations.find(a=>a.name==='Running_A')).play();mixer.update(.4);instance.updateMatrixWorld(true);let meshes=0,skins=0;instance.traverse(o=>{if(o.isMesh){meshes++;if(o.isSkinnedMesh){skins++;assert.ok(o.skeleton.bones.every(Boolean));}assert.ok(o.geometry.attributes.position.count>0);}});const hand=instance.getObjectByName('handslotr');assert.ok(hand,`${name} attachment bone missing`);const bounds=new THREE.Box3().setFromObject(instance),size=bounds.getSize(new THREE.Vector3());assert.ok(size.y>1&&size.y<5);console.log('PASS model',name,{meshes,skins,animations:data.animations.length,size:size.toArray().map(x=>+x.toFixed(2)),attachment:hand.name});}
globalThis.__YOURWAR_TEST__=true;globalThis.window=globalThis;globalThis.Audio=class{addEventListener(){} play(){return Promise.resolve()} pause(){}};globalThis.localStorage={getItem:()=>null};
const app=await import('../dist/game.mjs');
for(const name of ['Knight','Mage','Barbarian','Rogue_Hooded']){const b=await fs.readFile(new URL(`../dist/assets/models/${name}.glb`,import.meta.url));app.models.set(name,await new GLTFLoader().parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),''));}
for(const type of ['swordsman','guardian','pikeman','archer','berserker','bomber','healer','giant']){for(const team of [0,1]){const v=app.createUnitView(type,team,team);v.mixer.update(.5);v.root.updateMatrixWorld(true);let count=0;v.root.traverse(o=>{if(o.isMesh&&o.visible)count++;});assert.ok(count>=7);assert.equal(Object.keys(v.actions).length,5);assert.equal(v.root.children.length,2);console.log('PASS equipped unit',type,team,{visibleMeshes:count,animations:Object.keys(v.actions).length});}}

for(const [w,h] of [[1440,900],[390,844],[844,390]]){const layout=app.cameraLayout(w,h,37),camera=new THREE.PerspectiveCamera(43,w/h,.1,420);camera.position.set(Math.sin(.42)*Math.cos(.91)*layout.distance,Math.sin(.91)*layout.distance,Math.cos(.42)*Math.cos(.91)*layout.distance);camera.lookAt(0,0,0);camera.setViewOffset(w,h,0,layout.offsetY,w,h);camera.updateMatrixWorld();for(const x of [-10,10])for(const z of [-4.8,4.8]){const p=new THREE.Vector3(x,1,z).project(camera);assert.ok(Math.abs(p.x)<1&&Math.abs(p.y)<1,'default formation offscreen');const y=(1-p.y)*h/2;assert.ok(y<h-(h<560?150:200),'default formation behind bottom toolbar');}console.log('PASS camera formation framing',w,h);}
